cat <<EOF | kubectl apply -f -
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocdtesting
  namespace: argocd
spec:
  destination:
    namespace: argocdtesting
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: $HTTPS_REPO_URL
    path: ./k8s
    targetRevision: master
EOF